### PR TITLE
NVIDIA: Bump to 515.76.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Can't find egl-wayland even though it is listed in DEPENDS as a depends.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by esselfe** [comment]
Passed on my laptop with linux-lts 5.15.85.

**Pull request merged**
