### PR TITLE
提交者：lhw828 <http://allogs.ml>

### PR DESCRIPTION
**Pull request by lhw828**
Changed download URLs to use https
	change:     data/xkeyboard-config/DETAILS
	change:     driver/NVIDIA/DETAILS
	change:     driver/xf86-video-amdgpu/DETAILS
	change:     driver/xf86-video-nouveau/DETAILS
	change:     lib/libXfont2/DETAILS
	change:     lib/libdrm/DETAILS
	change:     lib/libevdev/DETAILS
	change:     lib/libpthread-stubs/DETAILS
	change:     lib/libtxc_dxtn/DETAILS
	change:     lib/libva/DETAILS
	change:     lib/libxcb/DETAILS
	change:     lib/libxklavier/DETAILS
	change:     lib/mesa-lib/DETAILS
	change:     lib/xcb-util-cursor/DETAILS
	change:     lib/xcb-util-image/DETAILS
	change:     lib/xcb-util-wm/DETAILS
	change:     lib/xcb-util/DETAILS
	change:     lib/xpyb/DETAILS
	change:     proto/xcb-proto/DETAILS
	change:     utils/xcb-util-keysyms/DETAILS
	change:     utils/xcb-util-renderutil/DETAILS
	change:     utils/xdg-user-dirs/DETAILS
	change:     utils/xdg-utils/DETAILS

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
Build finished.

**Comment by lunar-linux-b01** [comment]
Build finished.

**Comment by v4hn** [comment]
@lhw828 It would be great if you could try to avoid chinese characters in pull-requests / commits.
Most people I know in the Open Source community can't read or understand them.

Apart from that the changes look good. I'll leave it to @Ratler to sort out the test failure.

**Comment by lhw828** [comment]
@v4hn ok,Next time in English.

**Pull request merged**
