### PR TITLE
mesa-lib: drastically simplify CONFIGURE

### PR DESCRIPTION
**Pull request by v4hn**
- force egl, xa, gles1, gles2 and gbm. They shouldn't break anything

- add osmesa. This is a standalone addition some stuff already depends on

### CODE REVIEW

**Comment by sofar** [comment]
Fine with me, as long as gallium remains optional this should be fine :)

**Comment by Florin65** [comment]
for gallium (libosmesa) the swrast option must be on or we get a compile error. So, for this option it need to be forced on somehow.

**Comment by v4hn** [comment]
You're right, I missed that.

To fix this, I'd like to propose to always enable
the swrast option (in gallium as well as in DRI).
Technically only the gallium driver really is needed,
but I suppose it's a good idea to have the software
backend available anyways.

Awaiting feedback on this change,


v4hn

**Comment by Ratler** [comment]
Sounds like a good compromise. I will test it out now.

**Pull request merged**
