### PR TITLE
xf86-video-ati: version bump

### PR DESCRIPTION
**Pull request by rtlanceroad**

### CODE REVIEW

**Comment by rtlanceroad** [comment]
please retest

**Comment by rtlanceroad** [comment]
The header glamor.h is provided by xorg-server, well....

**Comment by Ratler** [comment]
@rtlanceroad the problem is most likely that your xorg-server is missing --enable-glamor.

**Comment by rtlanceroad** [comment]
@Ratler Indeed. libepoxy lists as optional depends part of xorg-server, but jenkins bot never builds it.

**Comment by Ratler** [comment]
The CI will only build optional_dependencies that are set to the default "y".

**Comment by Florin65** [comment]
I have incorporated it in the Driver PR.
Thank you for pointing it out.

**Comment by rtlanceroad** [comment]
@Florin65 Thanks, i'll close this one.

**Pull request closed without merging**
