### PR TITLE
X org7 - fix the problem of build time by splitting the process in more parts.

### PR DESCRIPTION
**Pull request by Florin65**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by v4hn** [comment]
What problem does this fix exactly?

**Comment by Florin65** [comment]
the buikd time for 'lin XOrg7' for exemple was measured in hours before it. now on a usual 64 bits machine it can be build (from scratch) in a fraction of the time, that's because the calculus for the depends is growing exponentially with the number of packages in the DEPENDS file.

**Comment by Florin65** [comment]
and the memory consumption too.

**Comment by Florin65** [comment]
in addition, with this PR applied some other lin commands work without a problem (lin mesa-lib, lin xorg-server for example). all starting from a fresh core install.

**Comment by v4hn** [comment]
If this patch works to drastically reduce the time needed for dependency analysis,
there should probably be a way to speed up things in the lunar tools...
But if it solves the problem, that's good enough for me...

I just read through the changes and they make sense to me.
As it is quite hard for me to test them over here, I'll leave the test&merge to @Ratler though.

**Pull request closed without merging**
